services:
  app-service:
    image: insecureee/app-service # specify name of image on Docker Hub
    restart: "no"
    environment: # set up environment variables
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost} # Use localhost as the default value
    ports:
      - "7000:7000" # expose port 7000 so that applications outside the container can connect to it
    depends_on: # only run app-service after auth-service has started
      auth-service:
        condition: service_started
  auth-service:
    image: insecureee/auth-service
    restart: "no"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    ports:
      - "3000:3000" # expose port 3000 so that applications outside the container can connect to it
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    restart: "no"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local